### ISSUE TITLE
Opening a program after closing one results in an error

### ISSUE THREAD

**Issue by sacredgeo** [matt-way/0x00#6]
If I close the window then try opening a program (either another program or the same one) I receive this error:

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: Attempted to register a second handler for 'ipc-engine-set-bounds'
at IpcMainImpl.handle (node:electron/js2c/browser_init:193:337)
at handle (/Users/.../0x00/src/ipc/main.js:4:18)
at initialiseEngineWindow (/Users/.../0x00/src/electron-app/engine.js:36:3)
at BrowserWindow.<anonymous> (/Users/.../0x00/src/electron-app/main.js:44:5)
at Object.onceWrapper (node:events:509:28)
at BrowserWindow.emit (node:events:390:28)
at BrowserWindow.emit (node:domain:475:12)
at node:electron/js2c/browser_init:161:13121
at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

I'm using "..." instead of my username. Anyway, once I click "Okay" I can go back to the menu and open the program without any issues.

**Comment by matt-way** [comment]
For now i've turned off the usual mac behaviour (when closing the window, it actually shuts the process down). In the future I'll look at building a more traditional way.
